:MSOffice:M::\x50\x4b::/usr/local/bin/office-wrapper:
:WordE:E::docx::/usr/local/bin/office-wrapper:
:ExcelE:E::xlsx::/usr/local/bin/office-wrapper:
:ExcelM:E::xlsm::/usr/local/bin/office-wrapper:
:ExcelOE:E::xls::/usr/local/bin/office-wrapper:
:PowerPointE:E::pptx::/usr/local/bin/office-wrapper:
:PowerPointOE:E::ppt::/usr/local/bin/office-wrapper:
