#!/bin/bash
powerExe=""
{
if ( command -v powershell.exe )
then
  powerExe="$(which powershell.exe)"
elif ( command -v "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" )  
then
  powerExe='/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe' 
elif ( command -v "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" ) 
then
  powerExe='/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe' 
elif ( command -v pwsh.exe )
then
  powerExe="$(which pwsh.exe)"
elif ( command -v "/mnt/c/Program Files/PowerShell/7/pwsh.exe" ) 
then
  powerExe="/mnt/c/Program Files/PowerShell/7/pwsh.exe" 
else
  drives=$(grep -i 9p /proc/mounts|grep -oi " /mnt/. ")
  for drive in ${drives}
  do
    if ( command -v "/mnt/${drive}/Windows/System32/WindowsPowerShell/v1.0/powershell.exe" ) 
    then
      powerExe="/mnt/${drive}/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
    fi
  done
fi
} > /dev/null

if [ -z "${powerExe}" ]
then
  echo powershell executable could not be found, exiting.
  exit 1
fi

args=( "$@" )
newargs=()
for var in "${args[@]}"
do
	if [ -e "${var}" ]
	then
		nextitem=$(wslpath -w "$(realpath "${var}")")
	else
		nextitem="${var}"
	fi
	newargs+=("${nextitem}")
done
"${powerExe}" -file "${newargs[0]}" "${newargs[@]:1}"
