#!/bin/bash
arg=("$@")
args=("${arg[@]:2}")
newargs=()
for var in "${args[@]}"
do
	if [ -e "${var}" ]
	then
		nextitem=$(wslpath -w "$(realpath "${var}")")
	else
		nextitem="${var}"
	fi
	newargs+=("${nextitem}")
done
/init "${1}" "${2}" "${newargs[@]}"