#!/bin/bash
targetDir=$HOME/.local/bin
mkdir -p "${targetDir}"
cd "${targetDir}"
if [[ "$1" == "-h" || -z "$1" ]]; then
  echo syntax: $0 [-f] [windows executable]
  echo use the -f switch if the windows executable needs a filename as a parameter so that WSL path will be mapped to windows path
  echo make sure "$targetDir}" is in your path
  exit 0
fi

if [ "$1" == "-f" ]; then
  map=1
  shift
fi

if [ -L "${targetDir}"/"${1}" ]; then
  echo overwriting existing "${1}"
  rm "${targetDir}"/"${1}"
elif [ -e "${targetDir}"/"${1}" ]; then
  echo "${1}" exists but is not a symlink, exiting.
  exit 1
fi

target="${targetDir}/${1}"
if (which "${1}".ps1); then
  echo '#!/bin/bash' >"${target}"
  if [ "$map" ]; then
    echo 'rp=$(realpath "$1")' >>"${target}"
    echo 'arg=$(wslpath -w "$rp")' >>"${target}"
    echo "powershell -file '"$(wslpath -w $(which "${1}".ps1))"' "'"$arg"' >>"${target}"
  else
    echo "powershell -file '"$(wslpath -w $(which "${1}".ps1))"' \$@" >>"${target}"
  fi
  chmod u+x "${target}"
  echo success: "${1}".ps1 mapped to "${target}"
  exit 0
fi

if [ -z "${map}" ]; then
  ln -s "$(which $1.exe)" "$1" || ln -s "$(which $1.cmd)" "$1" || ln -s "$(which $1.bat)" "${target}"
else
  target="${targetDir}/${1}-link"
  if [ -L "${target}" ]; then
    echo overwriting existing "${target}"
    rm "${target}"
  elif [ -L "${target}" ]; then
    echo "${target}" already exists as a file, exiting
    exit 1
  fi

  ln -s "$(which $1.exe)" "${target}" || ln -s "$(which $1.cmd)" "${target}" || ln -s "$(which $1.bat)" "${target}"
  echo '#!/bin/bash' >> "${targetDir}"/"${1}"
  echo 'rp=$(realpath "$1")' >> "${targetDir}"/"${1}"
  echo 'arg=$(wslpath -w "$rp")' >> "${targetDir}"/"${1}"
  echo "\"${target}\" \"\$arg\"" >> "${targetDir}"/"${1}"
  chmod u+x "${targetDir}"/"${1}"
  echo success: "${1}" mapped to "${targetDir}"/"${1}"
  exit 0
fi
