#!/bin/bash
targetDir=$HOME/.local/bin
mkdir -p "${targetDir}"
cd "${targetDir}"
if [[ "$1" == "-h" || -z "$1" ]]; then
  echo syntax: $0 [-f] [windows executable]
  echo use the -f switch if the windows executable needs a filename as a parameter so that WSL path will be mapped to windows path
  echo make sure "$targetDir}" is in your path
  exit 0
fi

if [ "$1" == "-f" ]; then
  map=1
  shift
fi

if [ -L ./"${1}" ]; then
  echo overwriting existing "${1}"
  rm ./"${1}"
elif [ -e ./"${1}" ]; then
  echo "${1}" exists but is not a symlink, exiting.
  exit 1
fi

if (which "${1}".ps1); then
  echo '#!/bin/bash' >./"${1}"
  if [ "$map" ]; then
    echo 'rp=$(realpath "$1")' >>./"${1}"
    echo 'arg=$(wslpath -w "$rp")' >>./"${1}"
    echo "powershell -file '"$(wslpath -w $(which "${1}".ps1))"' "'"$arg"' >>./"${1}"
  else
    echo "powershell -file '"$(wslpath -w $(which "${1}".ps1))"' \$@" >>./"${1}"
  fi
  chmod u+x ./"${1}"
  exit 0
fi

if [ -z "${map}" ]; then
  ln -s "$(which $1.exe)" "$1" || ln -s "$(which $1.cmd)" "$1" || ln -s "$(which $1.bat)" "${1}"
else
  target="${targetDir}/${1}-link"
  if [ -L "${target}" ]; then
    echo overwriting existing "${target}"
    rm "${target}"
  elif [ -L "${target}" ]; then
    echo "${target}" already exists as a file, exiting
    exit 1
  fi

  ln -s "$(which $1.exe)" "${target}" || ln -s "$(which $1.cmd)" "${target}" || ln -s "$(which $1.bat)" "${target}"
  echo '#!/bin/bash' >>./"${1}"
  echo 'rp=$(realpath "$1")' >>./"${1}"
  echo 'arg=$(wslpath -w "$rp")' >>./"${1}"
  echo "\"${target}\" \"\$arg\"" >>./"${1}"
  chmod u+x ./"${1}"
fi
